Description of my_meshgrid
Home > dtbb > util > my_meshgrid.m
my_meshgrid
PURPOSE
SYNOPSIS
function [xx,yy,s] = my_meshgrid(x,y)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_domain
get_domain_pts
squeeze_models [subms,filters,model_out] = squeeze_models(modelc)
SOURCE CODE
function [xx,yy,s] = my_meshgrid(x,y)
xx = single(x(:))';
yy = single(y(:));
nx = length(xx); ny = length(yy);
s  = [nx,ny];
xx = xx(ones(ny, 1),:);
yy = yy(:,ones(1, nx));
xx = xx(:)';
yy = yy(:)';