Description of imgdetect_bb_lookup
Home > dtbb > imgdetect_bb_lookup.m
imgdetect_bb_lookup
PURPOSE
[dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
SYNOPSIS
function [times_c,dets,boxes,is,tr,domain_kdtree,pyra] = imgdetect_bb_lookup(im,model_all,thrs,nmax,f_errs,pyra)
DESCRIPTION
 [dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
 fast object detection using dual-tree branch&bound/cascaded detection
 Inputs:
 im:           input image
 models_cell:  cell array of models - generated as in the demo_* scripts
 thr:          no hypothesis below this threshold will be retrieved
 nmax:         max # of detections. Set to negative value to get all
 detections above threshold (cascaded detection is used for that).
 Set to integer number, k, to get at most k configurations (BB is used for
 that). BB will stop if the upper bound of an interval is below thr
 Outputs:
 Detection data:
 dets,boxes,is:    identical with the outputs of imgdetect (Felzenszwalb & co)
 Timing data
 times:            (1): pyramid (2): unary (3): kdtrees (4:end): search
 Display data:
 tr:               keeps track of visited domain tree nodes,scores, etc
 domain_kdtree:    domain tree
 Copyright (C) 2012 Iasonas Kokkinos
 available under the terms of the GNU GPLv2
CROSS-REFERENCE INFORMATION
This function calls:
get_domain_kdtree
get_unary
quantizepyramid
sol2boxes % turn the outputs of branch and bound into original DPM format
expand_structure
This function is called by:
SOURCE CODE
function [times_c,dets,boxes,is,tr,domain_kdtree,pyra] = imgdetect_bb_lookup(im,model_all,thrs,nmax,f_errs,pyra)
% [dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
% fast object detection using dual-tree branch&bound/cascaded detection
% Inputs:
% im:           input image
% models_cell:  cell array of models - generated as in the demo_* scripts
% thr:          no hypothesis below this threshold will be retrieved
% nmax:         max # of detections. Set to negative value to get all
% detections above threshold (cascaded detection is used for that).
% Set to integer number, k, to get at most k configurations (BB is used for
% that). BB will stop if the upper bound of an interval is below thr
%
% Outputs:
% Detection data:
% dets,boxes,is:    identical with the outputs of imgdetect (Felzenszwalb & co)
% Timing data
% times:            (1): pyramid (2): unary (3): kdtrees (4:end): search
% Display data:
% tr:               keeps track of visited domain tree nodes,scores, etc
% domain_kdtree:    domain tree
%
% Copyright (C) 2012 Iasonas Kokkinos
% available under the terms of the GNU GPLv2
%[submodels,filters,model0] = squeeze_models(models_cell);
times = zeros(1,4);
model_all.sbin = 8;
model_all.interval = 10;
if ~exist('pyra','var')
    tic;
    [pyra]          = featpyramid(im, model_all);
    times(1)        = toc;
    pyra            = quantizepyramid(pyra,model_all.vocab,0);
end
interval        = model_all.interval;
levels_wt       = [[interval+1]:length(pyra.feat)];
%%----------------------------------------------------------------------
%% get unary terms & construct associated kd-trees
%%----------------------------------------------------------------------
%[part_trees,root_trees,domain_kdtree,bs,times] = front_end_lookup(model_all,levels_wt,pyra,...
%    model_all.scores_part,model_all.scores_root,model_all.nrm_all_part,model_all.nrm_all_root,...
%    model_all.submodels,interval,fc_err,times);
structure = model_all; expand_structure;
doa = 1;
for f_ind = 1:length(f_errs),
    times_c{f_ind} = times(1);
    fct_err = f_errs(f_ind);
    unary = tic;
    for l = 1:length(levels_wt),
        level     = levels_wt(l);
        [root_trees{l},~,grh,grv]  = get_unary(pyra,level,         allr,blocksize_root,bwr,offsr,bs,doa,scores_root,nrmr,single(fct_err));
        part_trees{l}            = get_unary(pyra,level-interval,allp,blocksize_part,bwp,offsp,[],doa,scores_part,nrmp,single(fct_err));
        if l==1
            domain_kdtree = get_domain_kdtree(grh,grv);
        end
    end
    times_c{f_ind}(2) = toc(unary);
    %%----------------------------------------------------------------------
    %% combine
    %%----------------------------------------------------------------------
    nparts  = 8;
    %% in general {nmax, thr} will be scalars, so the code below will amount to
    %%  [i,v,tr]  = mex_traverse(root_trees,part_trees,nparts,domain_kdtree,thr(1),nmax(1));
    %% but if we to generate plots by gathering timings for multiple values of
    %% thr/nmax, we send these in as vectors and use the for-for loop below
    cn = 0;
    bs  = single([model_all.submodels.svm_b]);
    for id = 1:length(nmax)
        for k = 1:length(thrs)
            tic;
            [i,v,tr]  = mex_traverse(root_trees,part_trees,nparts,domain_kdtree,thrs(k),nmax(id),...
                1,pyra.featp,pyra.padx+1,pyra.pady+1,model_all.w_root,model_all.w_part,bs);
            cn = cn + 1;
            times_c{f_ind}(2+cn) = toc;
            if nargout>1,
                scales = pyra.scales(interval+1:end);
                nobjs  = length(submodels)/6;
                [dets{f_ind,cn},boxes{f_ind,cn},is] = sol2boxes(i,v,submodels,scales,nobjs,root_trees,part_trees);
            end
        end
    end
    scales  = [];
    nobjs   = [];
end
if (length(nmax)*length(thrs)==1)&(nargout>1)
    dets = dets{1,1};
    boxes = boxes{1,1};
end
%scales          = pyra.scales(interval+1:end);
%nobjs           = length(models_cell);
%[dets,boxes,is] = sol2boxes(i,v,submodels,scales,nobjs,root_trees,part_trees);