Description of imgdetect_bb
Home > dtbb > imgdetect_bb.m
imgdetect_bb
PURPOSE
[dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
SYNOPSIS
function [dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
DESCRIPTION
 [dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
 fast object detection using dual-tree branch&bound/cascaded detection
 Inputs:
 im:           input image
 models_cell:  cell array of models - generated as in the demo_* scripts
 thr:          no hypothesis below this threshold will be retrieved
 nmax:         max # of detections. Set to negative value to get all
 detections above threshold (cascaded detection is used for that).
 Set to integer number, k, to get at most k configurations (BB is used for
 that). BB will stop if the upper bound of an interval is below thr
 Outputs:
 Detection data:
 dets,boxes,is:    identical with the outputs of imgdetect (Felzenszwalb & co)
 Timing data
 times:            (1): pyramid (2): unary (3): kdtrees (4:end): search
 Display data:
 tr:               keeps track of visited domain tree nodes,scores, etc
 domain_kdtree:    domain tree
 Copyright (C) 2012 Iasonas Kokkinos
 available under the terms of the GNU GPLv2
CROSS-REFERENCE INFORMATION
This function calls:
front_end
sol2boxes % turn the outputs of branch and bound into original DPM format
squeeze_models [subms,filters,model_out] = squeeze_models(modelc)
This function is called by:
SOURCE CODE
function [dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
% [dets,boxes,is,times,tr,domain_kdtree] = imgdetect_bb(im,models_cell,thr,nmax)
% fast object detection using dual-tree branch&bound/cascaded detection
% Inputs:
% im:           input image
% models_cell:  cell array of models - generated as in the demo_* scripts
% thr:          no hypothesis below this threshold will be retrieved
% nmax:         max # of detections. Set to negative value to get all
% detections above threshold (cascaded detection is used for that).
% Set to integer number, k, to get at most k configurations (BB is used for
% that). BB will stop if the upper bound of an interval is below thr
%
% Outputs:
% Detection data:
% dets,boxes,is:    identical with the outputs of imgdetect (Felzenszwalb & co)
% Timing data
% times:            (1): pyramid (2): unary (3): kdtrees (4:end): search
% Display data:
% tr:               keeps track of visited domain tree nodes,scores, etc
% domain_kdtree:    domain tree
%
% Copyright (C) 2012 Iasonas Kokkinos
% available under the terms of the GNU GPLv2
[submodels,filters,model0] = squeeze_models(models_cell);
times = zeros(1,4);
tic;
[pyra]          = featpyramid(im, model0);
times(1)        = toc;
interval        = model0.interval;
levels_wt       = [[interval+1]:length(pyra.feat)];
%%----------------------------------------------------------------------
%% get unary terms & construct associated kd-trees
%%----------------------------------------------------------------------
[part_trees,root_trees,domain_kdtree,times] = front_end(model0,levels_wt,pyra,filters.allr,filters.allp,submodels,interval,times);
%%----------------------------------------------------------------------
%% combine
%%----------------------------------------------------------------------
nparts  = 8;
%% in general {nmax, thr} will be scalars, so the code below will amount to
%%  [i,v,tr]  = mex_traverse(root_trees,part_trees,nparts,domain_kdtree,thr(1),nmax(1));
%% but if we to generate plots by gathering timings for multiple values of
%% thr/nmax, we send these in as vectors and use the for-for loop below
cn = 0;
for id = 1:length(nmax)
    for k = 1:length(thr)
        tic;
        [i,v,tr]  = mex_traverse(root_trees,part_trees,nparts,domain_kdtree,thr(k),nmax(id));
        cn = cn + 1;
        times(3+cn) = toc;
    end
end
scales = pyra.scales(interval+1:end);
nobjs  = length(models_cell);
[dets,boxes,is] = sol2boxes(i,v,submodels,scales,nobjs,root_trees,part_trees);